Add status check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,11 +18,15 @@ jobs:
         run: |
           echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
           echo "https://github.com/${{ github.event.client_payload.repository }}/commit/${{ github.event.client_payload.sha }}"
+          echo "::set-output name=link::https://github.com/${{ github.event.client_payload.repository }}/commit/${{ github.event.client_payload.sha }}"
           echo "::set-output name=sha_short::$(echo ${{ github.event.client_payload.sha }} | cut -c1-7)"
       - name: Run w3c/mdn-spec-links build
         id: build
         if: github.event.action == 'ping'
-        run: make report-BCD && make report
+        run: |
+          echo "::set-output name=conclusion::success"
+          make report-BCD || echo "::set-output name=conclusion::failure"
+          make report || echo "::set-output name=conclusion::failure"
       - uses: crazy-max/ghaction-import-gpg@v3
         with:
           gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
@@ -30,6 +34,7 @@ jobs:
           git-user-signingkey: true
           git-commit-gpgsign: true
       - name: Create pull request
+        if: ${{ steps.build.outputs.conclusion == 'success' }}
         id: cpr
         uses: peter-evans/create-pull-request@v3
         with:
@@ -45,5 +50,24 @@ jobs:
           branch-suffix: timestamp
           delete-branch: true
       - name: Log pull request URL
+        if: ${{ steps.build.outputs.conclusion == 'success' }}
         run: |
           echo "Pull request URL: ${{ steps.cpr.outputs.pull-request-url }}"
+      - name: Set status
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          BUILD_COMMIT=$(git rev-parse HEAD)
+          curl \
+          -X POST \
+          -H "Authorization: Bearer $GITHUB_TOKEN" \
+          -H "Accept: application/vnd.github.v3+json" \
+          https://api.github.com/repos/w3c/mdn-spec-links/check-runs \
+          -d '{"name":"build", "head_sha": "'"$BUILD_COMMIT"'", "status": "completed", "conclusion": "${{ steps.build.outputs.conclusion }}" }'
+          curl \
+          -X POST \
+          -H "Authorization: Bearer $GITHUB_TOKEN" \
+          -H "Accept: application/vnd.github.v3+json" \
+          https://api.github.com/repos/w3c/mdn-spec-links/statuses/${{ github.sha }} \
+          -d '{"state": "${{ steps.build.outputs.conclusion }}", "target_url": "https://github.com/w3c/mdn-spec-links/actions/runs/${{ github.run_id }}?check_suite_focus=true", "context": "Build triggered by ${{ github.event.client_payload.repository }} changes" }'
+          if [[ "${{ steps.build.outputs.conclusion }}" == "failure" ]]; then exit 1; fi
