CI: For SPECURLS.json, don’t also run full build

diff --git a/.github/workflows/build-spec-urls.yml b/.github/workflows/build-spec-urls.yml
--- a/.github/workflows/build-spec-urls.yml
+++ b/.github/workflows/build-spec-urls.yml
@@ -19,13 +19,8 @@ jobs:
       - name: Run SPECURLS.json build
         id: incoming
         run: |
-          make URLS-LOG
-      - name: Run w3c/mdn-spec-links build
-        id: build
-        run: |
           echo "{name}={conclusion::success}" >> $GITHUB_OUTPUT
-          make report-BCD || echo "{name}={conclusion::failure}" >> $GITHUB_OUTPUT
-          make report || echo "{name}={conclusion::failure}" >> $GITHUB_OUTPUT
+          make URLS-LOG || echo "{name}={conclusion::failure}" >> $GITHUB_OUTPUT
       - uses: crazy-max/ghaction-import-gpg@v5
         with:
           gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
