CI: Fix syntax of outputs params

diff --git a/.github/workflows/build-spec-urls.yml b/.github/workflows/build-spec-urls.yml
--- a/.github/workflows/build-spec-urls.yml
+++ b/.github/workflows/build-spec-urls.yml
@@ -19,9 +19,9 @@ jobs:
       - name: Run SPECURLS.json build
         id: incoming
         run: |
-          echo "{name}={conclusion::success}" >> $GITHUB_OUTPUT
+          echo "conclusion=success" >> $GITHUB_OUTPUT
           make URLS-LOG \
-            || echo "{name}={conclusion::failure}" >> $GITHUB_OUTPUT; \
+            || echo "conclusion=failure" >> $GITHUB_OUTPUT; \
             exit 1
       - uses: crazy-max/ghaction-import-gpg@v3
         with:
